GET http://localhost:5000/api/localhost:5000/api/task

###

POST http://localhost:5000/api/user/signup
Content-Type: application/json

{
    "first": "Testo",
    "last": "Tester",
    "email": "testot@gmail.com",
    "password": "myTest1!",
    "password_confirmation": "myTest1!"
}

###

GET http://localhost:5000/api/user/63b5de0af491bc56d96f341f

###

POST  http://localhost:5000/api/user/login
Content-Type: application/json

{
    "email": "testet@gmail.com",
    "password": "myTest1!"
}

###

POST http://localhost:5000/api/task/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2JjNzQ1YTk2ZTM3N2U4ZjFkNDdiNGIiLCJpYXQiOjE2NzMzMzI1MDksImV4cCI6MTY3MzMzNjEwOX0.PDe-7wqDrIWPhOgLTmCNgKiynpJyrhAWXX2inlAEqwU

{
    "name": "new task w/ id 3",
    "completed": "true",
    "user_id": "63bc745a96e377e8f1d47b4b"
}

###

DELETE http://localhost:5000/api/user/63bb8a8a38a29eb3087f6e22