GET http://localhost:5000/api/task

###

POST http://localhost:5000/api/task/add
Content-Type: application/json

{
    "name": "New Task 2",
    "completed": false
}

###

PUT  http://localhost:5000/api/task/edit/63ae1e0af9ea4f9b9b961d0e
Content-Type: application/json

{
    "name": "task 4.1",
    "completed": true
}

###

GET http://localhost:5000/api/note