GET http://localhost:5000/api/user

###

POST http://localhost:5000/api/user/signup
Content-Type: application/json

{
    "first": "Test",
    "last": "Tester",
    "email": "testT@gmail.com",
    "password": "testB3",
    "password_confirmation": "testB3"
}

###

GET http://localhost:5000/api/user/63af26cc5674efd42f25fefe

###

POST  http://localhost:5000/api/user/login
Content-Type: application/json

{
    "email": "testerTA@gmail.com",
    "password": "testaA1"
}

###

DELETE http://localhost:5000/api/user/63af3fff7e6d501eb189ca1b